spring:
  application:
    name: favorite-service
  config:
    import: "configserver:http://localhost:8888"

  cloud:
    config:
      uri: http://localhost:8888      # Config Server 地址
      name: favorite-service             # Config Server 上的配置文件名称
      profile: default
    
