server:
  port: 8888  # 配置服务端口

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/your-repo/config-repo  # 配置文件存放的 Git 仓库
          searchPaths: config-files                  # Git 仓库中的路径
        # 如果使用本地文件系统，可以替换为 file:///path/to/config/files

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/  # Eureka 服务注册中心地址
