server:
  port: 8888  # 配置服务端口

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Hzeristo/price_comparison  # 配置文件存放的 Git 仓库
          searchPaths: config-server/src/main/resources/conf                 # Git 仓库中的路径

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/  # Eureka 服务注册中心地址
      registerWithEureka: true  # 是否注册到 Eureka
      fetchRegistry: true  # 是否从 Eureka 获取服务注册信息
      instance:
        hostname: main-service-host  # 服务实例的主机名
