server:
  port: 8888  # 配置服务端口

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file:///D:/Code/compare_spring/price_comparison_app/config-server/src/main/resources/config  

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/  # Eureka 服务注册中心地址
      registerWithEureka: true  # 是否注册到 Eureka
      fetchRegistry: true  # 是否从 Eureka 获取服务注册信息
      instance:
        hostname: config-server-host  # 服务实例的主机名
