server:
  port: 8082

jwt:
  secret: haydenshuihaydenshuihaydenshuihaydenshui
  expiration: 86400000  # 1 day in milliseconds
  
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3306/product_db
    username: root
    password: ""  # 注意：密码为空时，也可以设置为一个空字符串
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create  # 生成数据库表结构的方式，其他可选值：none, update, validate
    show-sql: true  # 打印 SQL 查询语句
    properties:
      hibernate:
        format_sql: true  # 格式化 SQL 输出
        use_sql_comments: true  # 在 SQL 中添加注释
  redis:
    host: 127.0.0.1
    port: 6379
    password: your_password  # 如果有密码的话
    timeout: 2000  # 超时时间

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka  # Eureka 服务器地址
    registerWithEureka: true  # 是否注册到 Eureka
    fetchRegistry: true  # 是否从 Eureka 获取服务注册信息
    instance:
      prefer-ip-address: false
      hostname: item-service-host  # 服务实例的主机名
  server:
    enable-self-preservation: false  # 禁用自我保护机制
