server:
  port: 8080

spring:
  application:
   name: main-service

  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka  # Eureka 服务器地址
      registerWithEureka: true  # 是否注册到 Eureka
      fetchRegistry: true  # 是否从 Eureka 获取服务注册信息
      instance:
        hostname: item-service-host  # 服务实例的主机名
    server:
      enable-self-preservation: false  # 禁用自我保护机制
  
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # 启用 Eureka 服务发现
      globalcors:
        corsConfigurations:
          '[/**]':  # 跨域支持
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: false
      routes:
        - id: user-service  # 定义路由 ID
          uri: lb://user-service  # 使用 Eureka 服务发现，通过负载均衡访问 user-service 服务
          predicates:
            - Path=/user/**  # 设置路由匹配规则
          filters:
            - StripPrefix=1  # 删除请求路径的前缀
        - id: item-service  # 定义另一个路由
          uri: lb://item-service  # 使用 Eureka 服务发现，负载均衡访问 item-service
          predicates:
            - Path=/item/**  # 设置路由匹配规则
          filters:
            - StripPrefix=1  # 删除请求路径的前缀