server:
  port: 8091

jwt:
  secret: haydenshuihaydenshuihaydenshuihaydenshui
  expiration: 86400000  # 1 day in milliseconds

jd:
  url:
    login: https://passport.jd.com/new/login.aspx
    search: https://search.jd.com/Search?keyword=
    item: https://item.jd.com/

taobao:
  url:
    login: https://login.taobao.com/
    search: https://s.taobao.com/search?page=1&q=

webdriver:
  edge:
    driver:
      path: "E:/edgedriver_win64/msedgedriver.exe"


spring:
  application:
    name: spider-service
  datasource:
    enabled: false
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka  # Eureka 服务器地址
    registerWithEureka: true  # 是否注册到 Eureka
    fetchRegistry: true  # 是否从 Eureka 获取服务注册信息
    instance:
      prefer-ip-address: false
      hostname: auth-service-host  # 服务实例的主机名
  server:
    enable-self-preservation: false  # 禁用自我保护机制